### ISSUE TITLE
please create a nuget package from this

### ISSUE THREAD

**Issue by penCsharpener** [krugertech/SMART.Net#1]
title says it all

**Comment by krugertech** [comment]
I've made a note. Will get to it soon.

**Comment by yngvesl** [comment]
Hi. Thanks for a great project. Any progress on this issue?

**Comment by krugertech** [comment]
> Hi. Thanks for a great project. Any progress on this issue?

Hey @yngvesl 
Someone else is already using a Nuget package with the ID "SMART.Net" for another unrelated project.
I'm looking into renaming the project and publishing a NuGet package.

**Comment by krugertech** [comment]
@penCsharpener , @yngvesl 
Latest Nuget available here -> https://www.nuget.org/packages/Krugertech.IO.Smart

Note that 
1. The namespace has been updated from Simplified.IO to Krugertech.IO.
2. Usage changed from Smart.GetDrives() to SmartDrive.GetDrives()

**Comment by Matzeeee** [comment]
can anybody please help me to get the Nuget packet installed in VB NET (framework 2.0)?
i get error:
![grafik](https://user-images.githubusercontent.com/60921150/165958127-edc73846-0891-40b4-b284-410a6008a200.png)

**Comment by krugertech** [comment]
@Matzeeee Hi There. The minimum supported .NET Framework version is 4.6.1. 
You will need to upgrade your Framework version in order to use it.

**Comment by Matzeeee** [comment]
for me it works with .NET 4.7.2
