### ISSUE TITLE
Can't read SMART from Nvme drives

### ISSUE THREAD

**Issue by Christian1980** [krugertech/SMART.Net#4]
The smart registers can't be read from a SSD  Nvme. Works fine for a SATA SSD.

Drive showing as "BAD".

![image](https://user-images.githubusercontent.com/11683257/123075948-f9316680-d418-11eb-91db-4cd865a3c996.png)

**Comment by krugertech** [comment]
Hi Christian. 

Apologies. I never seem to get any Github notifications.

From what I understood, NVME's don't officially support smart registers.
 
I see that Microsoft have added support for querying some information from these drives.  https://docs.microsoft.com/en-us/windows/win32/fileio/working-with-nvme-devices

Also there was an article I saw that said Win10 has added health checking of NVME drives. So there likely is a way to determine NVME health using their API's and SDKs.

Hope that helps.
