### ISSUE TITLE
Question: how to get current S.M.A.R.T. status

### ISSUE THREAD

**Issue by Matzeeee** [krugertech/SMART.Net#5]
I please want to know if i always have to recall "SmartDrive.GetDrives" if i want to get the current values of SMART attributes?

Is it possible to get SMART only for a special drive? Calling GetDrives takes some seconds on my machine to get ALL drives (i have 20 drives and some network drives mapped wich dont have SMART).

Thanks.

**Comment by krugertech** [comment]
It should be possible I think to filter the list of drives returned.

Checkout the WmiController class where the drives are being listed. 
Currently all drives are returned using this query.

`@"SELECT * FROM Win32_DiskDrive"`

So I believe this query could be extended with a WHERE filter. 
Another option would be to checkout the Win32_DiskDrive API docs and see if is possible to filter out network drives as I suspect/guess those drives are responsible for creating a delay when returning smart data.
