### ISSUE TITLE
Life time writes int type overflow

### ISSUE THREAD

**Issue by Case-Closed-X** [krugertech/SMART.Net#6]
Life time writes int type overflow, as shown in the screenshot. I'm not sure it's a problem, but it doesn't look quite right.
<img width="436" alt="Life time writes" src="https://user-images.githubusercontent.com/50199528/176345890-b3bea052-2478-41de-899b-4e8db637974d.png">

**Comment by krugertech** [comment]
Yes, that doesn't look right.

Can you please share the drive info you are testing against?

**Comment by Case-Closed-X** [comment]
@krugertech Sorry for getting back to you late. My drive is a 1TB HDD from Western Digital(WD10EZEX), is this screenshot OK?
![image](https://user-images.githubusercontent.com/50199528/180988079-407f5481-f14a-42ef-993d-32a17b3fcb96.png)

**Comment by krugertech** [comment]
Hi there. I finally had time to look at this.
Could you check if the latest source code resolves the issue for you?
