### ISSUE TITLE
Not able to detect the S.M.A.R.T information from a USB attached SCSI device

### ISSUE THREAD

**Issue by Fuzzy-Grey-Cat** [krugertech/SMART.Net#9]
i have an external hard drive plugged in and i ran the code but it keeps outputting "Not supported". is this because the hard drive is connected via USB? 

![image](https://github.com/krugertech/Krugertech.IO.Smart/assets/93584168/6c992381-952f-4d99-8585-e2b906ed46e1)

**Comment by krugertech** [comment]
Correct. USB is not supported.
